### ISSUE TITLE
watcher.js error

### ISSUE THREAD

**Issue by muranava** [FeelTrainCoop/101atron#1]
## hi getting this when running watcher.js, am on OSX 10.9.5

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Bad Twitter streaming request: 401
    at ClientRequest.<anonymous> (/Users/mura/101atron/101atron-master/node_modules/twit/lib/oarequest.js:202:19)
    at ClientRequest.g (events.js:199:16)
    at ClientRequest.emit (events.js:107:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming](_http_client.js:426:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
    at TLSSocket.socketOnData (_http_client.js:317:20)
    at TLSSocket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at TLSSocket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)

---

**Comment by muranava** [comment]
oops sorry one of the access keys had an extra space in it
